In [1]:
# pip install pandas sqlalchemy pymysql cryptography

# Cargar librerias 
import pandas as pd
from sqlalchemy import create_engine, text

In [2]:
# Datos de Conexion BD
usuario = 'mi_usuario'
contrasena = 'mi_password'
host = 'localhost'
puerto = 3306
base_de_datos = 'mi_base_de_datos'

In [3]:
# Cargar data y vista previa
df = pd.read_csv('DataSetFinalProyectoGradoMIAD.csv') 
df.head()

,PB_DANE,Cluster,INDICADOR,Depósitos en cuenta corriente bancaria,Cuentas de ahorro especial,Porc_trabajos_formales,Total_Monto_Microcredito,Total_Monto_Credito de vivienda,Total_Monto_Credito de consumo,Total_Numero_Transacciones corresponsal movil,Créditos de vivienda,Total_Numero_Numero de corresponsales moviles,Total_Numero_Credito de consumo,CodigoM,Municipio,Código Entidad,Cobertura_edu_total,Cobertura_edu_media,Tasa_repitencia
0,5001,4,0.313208,2.151817e+07,827701.702331,0.6152,342432.552858,3.833396e+06,1.462338e+07,33688.0,4.727297e+07,424.0,7340898.0,5001,MEDELLIN,5001,97.06,56.18,6.41
1,5031,0,0.292885,3.069776e+04,122.287054,0.1216,3031.182200,4.211532e+03,9.556226e+03,0.0,4.774004e+04,4.0,11528.0,5031,AMALFI,5031,71.63,28.92,7.48
2,5045,6,0.168077,3.002729e+05,3885.496312,0.2910,29134.726425,3.125486e+04,2.487893e+05,27.0,6.700035e+05,15.0,103939.0,5045,APARTADO,5045,94.91,57.86,5.56
3,5147,0,0.217514,9.823691e+04,341.081890,0.1067,10511.834182,1.536979e+03,2.287370e+04,33.0,3.435686e+04,9.0,13105.0,5147,CAREPA,5147,94.16,45.83,7.48
4,5266,6,0.439943,6.271394e+05,81086.375849,0.2585,24514.106164,1.916579e+05,1.701604e+06,17.0,2.868979e+06,15.0,1094451.0,5266,ENVIGADO,5266,100.44,65.36,6.49

In [4]:
# Modificacion a BD
# df.rename(columns={'Porc_part_Propósito general':'Porc_part_Proposito_general'}, inplace=True)

In [5]:
# Crear conexion BD
engine = create_engine(f'mysql+pymysql://{usuario}:{contrasena}@{host}:{puerto}/{base_de_datos}')

In [6]:
# Revisar conexion
engine.connect().execute(text("SHOW DATABASES")).fetchall()

[('information_schema',), ('mi_base_de_datos',), ('performance_schema',)]

In [7]:
# crear tabla con datos
df.to_sql('dataSetMIAD', con=engine, if_exists='replace', index=False)

81